<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Queues' => 'Kolejki',
  'Could not find queue' => 'Nie udało się odnaleźć kolejki',
  'Details' => 'Szczegóły',
  'Back to messages list' => 'Wróć do listy wiadomości',
  'List' => 'Lista',
  'Mark as read' => 'Oznacz jako przeczytaną',
  'Mark all as read' => 'Oznacz wszystkie jako przeczytane',
  'Message' => 'Wiadomość',
  'Message category' => 'Kategoria wiadomości',
  'Message content' => 'Treść wiadomości',
  'Message details' => 'Szczegóły wiadomości',
  'Message with given ID was not found' => 'Wiadomość o podanym ID nie została odnaleziona',
  'Messages' => 'Wiadomości',
  'New message' => 'Nowa wiadomość',
  'Newer' => 'Nowsze',
  'Older' => 'Starsze',
  'Subscriptions' => 'Subskrypcje',
  'Other recipients' => 'Pozostali odbiorcy',
  'Reply' => 'Odpowiedź',
  'Submit' => 'Wyślij',
  'View all messages' => 'Zobacz wszystkie wiadomości',
  'View messages' => 'Zobacz wiadomości',
);
