<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Create channel' => 'Utwórz kanał',
  'Update any channel' => 'Zaktualizuj dowolny kanał',
  'Delete any channel' => 'Usuń dowolny kanał',
  'Read any channel' => 'Czytaj dowolny kanał',
  'Read subscribed channel' => 'Czytaj subskrybowany kanał',
  'Subscribe to any channel' => 'Zapisz się do dowolnego kanału',
  'Read messages from any channel' => 'Czytaj wiadomości z dowolnego kanału',
  'Send messages to any channel' => 'Wysyłaj wiadomości do dowolnego kanału',
  'Read only subscribed channel' => 'Czytaj tylko subskrybowane kanały',
  'Unsubscribe from a subscribed channel' => 'Wypisz się z subskrybowanego kanału',
  'Read messages from subscribed channel' => 'Czytaj wiadomości z subskrybowanych kanału',
  'Send messages to subscribed channel' => 'Wysyłaj wiadomości do subskrybowanych kanałów',
);
